# Generated by Django 4.2.1 on 2023-06-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO list_list (name, color, user_id_id) VALUES ('First List', 'red', 1);"
            "DELETE FROM list_list WHERE id=1;"

        )
    ]
