# Generated by Django 4.2.1 on 2023-06-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_migration_add_first_list'),
    ]

    def insertData(apps, schema_editor):
        Login = apps.get_model('list', 'List')
        user = Login(id=1, name="Primeira lista", color="red", user_id_id=1)
        user.save()

    operations = [
        migrations.RunPython(insertData),
    ]
