# Generated by Django 4.2.1 on 2023-06-01 20:25

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='by_list',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='list.List'),
        )
    ]
