# Generated by Django 4.2.1 on 2023-06-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
        ('api', '0002_migration_add_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='by_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list'),
        ),
    ]
